### DISCUSSION TITLE
Impossible to connect to ext. eKuiper instances from ekuiper manager

### DISCUSSION THREAD

**Discussion by kriskonina** [lf-edge/ekuiper#3610] [Q&A]
How exactly does one provide a *valid* pair of `ak` and `sk`?

<img width="468" alt="image" src="https://github.com/user-attachments/assets/86e4c919-b802-4be3-b754-96332737a462" />

I tried putting `signature` block in `kuiper.yaml` like so:

```
signature:
  method: sha256
  ak: ...
  sk: ...
```

But can't even tell if this is recognized by ekuiper...

What's the way to achieve it?
