### ISSUE TITLE
Some questions about the eKuiper+Edgex

### ISSUE THREAD

**Issue by littletiger123** [lf-edge/ekuiper#1078]
**Please describe your problem in detail, if necessary, you can upload the log file through the attachment**:
I have tried the quick start and it succeeds. But I read the **edgex_rule_engine_tutorial.md** which is about the eKuiper and Edgex. I am a new one  so I have several questions about it 
1. Who create the data? Is the virtual device and where I can find it ?
2. I enter the docker container, and I found that **EDGEX__DEFAULT__SERVER=edgex-redis**  which means we do not use the MQTT server? Also, I change the **CONF_KEY **  and set it **mqtt_conf** when creating the steam, but it may not have an effect. So I want to know which yaml is used? **/kuiper/etc/mqtt_source.yaml** or **/kuiper/erc/sources/edgex.yaml**. And may you exlpain the different because I see the MQTT config occur in both YAML.
``` 
application_conf:
    port: 5571
    protocol: tcp
    server: localhost
    topic: application
default:
    optional:
        Password: y3sm8JQBDjAAb3IpEZzxUddzgq/aUMQBhJFIhaAMEwQl
        Username: redis5
    port: 6379
    protocol: redis
    server: edgex-redis
    serviceServer: http://localhost:48080
    topic: rules-events
    type: redis
mqtt_conf:
    optional:
        ClientId: client1
    port: 1883
    protocol: tcp
    server: 127.0.0.1
    topic: events
    type: mqtt
```
3. I changed the yaml file and I want to know how to apply the new yaml to the service?
Thanks a lot.
