### ISSUE TITLE
Redis Password logged by shared connection

### ISSUE THREAD

**Issue by lenny-intel** [lf-edge/ekuiper#1173]
**Environment**: 

- eKuiper version (e.g. `1.3.0`): `lfedge/ekuiper:1.4-alpine`
- Hardware configuration (e.g. `lscpu`): Intel x86
- OS (e.g. `cat /etc/os-release`): `Ubuntu 18.04 in WSL2`
- Others:

**What happened and what you expected to happen**:
Logs contain:
```
time="2022-02-09 17:48:19" level=info msg="open source node with props map[connectionSelector:edgex.redisMsgBus format:json optional:map[Password:eIn1VLWPlUoCozaFJVUaAcU3gVlUP47YQT3UzKQHdNS4 Username:redis5] port:6379 protocol:redis server:localhost topic:rules-events type:redis], concurrency: 1, bufferLength: 102400" file="node/source_node.go:91" rule=ruleEdgexSinkApp
```
**How to reproduce it (as minimally and precisely as possible)**:
Connect to Edgex Secure mode with following settings in EdgeX Compose file:
```
    environment:
      KUIPER__BASIC__DEBUG: "true"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__RESTPORT: 59720
      CONNECTION__EDGEX__REDISMSGBUS__PORT: 6379
      CONNECTION__EDGEX__REDISMSGBUS__PROTOCOL: redis
      CONNECTION__EDGEX__REDISMSGBUS__SERVER: edgex-redis
      CONNECTION__EDGEX__REDISMSGBUS__TYPE: redis
      EDGEX__DEFAULT__CONNECTIONSELECTOR: edgex.redisMsgBus
      EDGEX__DEFAULT__TOPIC: rules-events
```

**Anything else we need to know?**:
