### ISSUE TITLE
EdgeX mqtt message bus failed to connect to mqtt-broker with TLS enable

### ISSUE THREAD

**Issue by cherrycl** [lf-edge/ekuiper#1275]
**Environment**:

- eKuiper version (e.g. `1.3.0`):  lfedge/ekuiper:1.5-alpine,  lfedge/ekuiper:1.4-alpine
- Hardware configuration (e.g. `lscpu`): x86_64
- OS (e.g. `cat /etc/os-release`): ubuntu 20.04
- Others:

**What happened and what you expected to happen**:
```
time="2022-05-18 14:42:32" level=error msg="The connection to edgex messagebus failed." file="edgex/edgex.go:126"
time="2022-05-18 14:42:32" level=error msg="can not create client for cfg : map[ClientId:edgexsource certificationpath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.crt format:json insecureskipverify:true messagetype:request optional_keepalive:50 port:8883 privatekeypath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.key protocol:tcps rootcapath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/ca.crt server:mqtt-broker topic:edgex/events/# type:mqtt] have error Failed to connect to edgex message bus: An error occured while performing a 'Connect' operation: network Error : x509: certificate signed by unknown authority" file="clients/client_registy.go:103"
time="2022-05-18 14:42:32" level=error msg="found error when get edgex client, error Failed to connect to edgex message bus: An error occured while performing a 'Connect' operation: network Error : x509: certificate signed by unknown authority" file="source/edgex_source.go:80" rule=mqtt-tls-rule
```
**How to reproduce it (as minimally and precisely as possible)**:
1. Used the following environment variables to deploy ekuiper service.
```
environment:
      EDGEX__DEFAULT__PORT: 8883
      EDGEX__DEFAULT__PROTOCOL: tcps
      EDGEX__DEFAULT__SERVER: mqtt-broker
      EDGEX__DEFAULT__CLIENTID: edgexsource
      EDGEX__DEFAULT__CERTIFICATIONPATH: /tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.crt
      EDGEX__DEFAULT__PRIVATEKEYPATH: /tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.key
      EDGEX__DEFAULT__ROOTCAPATH: /tmp/edgex/secrets/mqtt/client/edgex-kuiper/ca.crt
      EDGEX__DEFAULT__INSECURESKIPVERIFY: 'true'
      EDGEX__DEFAULT__OPTIONAL_KEEPALIVE: 50
```
2. Create stream
```
{
    "sql": "create stream edgexsource() WITH (FORMAT=\"JSON\", TYPE=\"edgex\")"
}
```
3. Create rule
```
{
   "id": "mqtt-tls-rule",
   "sql": "SELECT * FROM edgexsource",
   "actions":[
      {
         "mqtt":{
            "certificationPath": "/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.crt",
            "clientId": "mqtt-tls-rule",
            "insecureSkipVerify": true,
            "privateKeyPath": "/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.key",
            "rootCaPath": "/tmp/edgex/secrets/mqtt/client/edgex-kuiper/ca.crt",
            "server": "tcps://mqtt-broker:8883",
            "topic": "export"
         }
      }
   ]
}
```

**Anything else we need to know?**:
[kuiper-connection-log.txt](https://github.com/lf-edge/ekuiper/files/8713875/kuiper-connection-log.txt)

mqtt-broker logs:
```
1652856152: New connection from 192.168.128.8:48118 on port 8883.
1652856152: New client connected from 192.168.128.8:48118 as mqtt-tls-rule (p1, c0, k30, u'edgex-kuiper').
1652856152: New connection from 192.168.128.8:48122 on port 8883.
1652856152: OpenSSL Error[0]: error:1404A412:SSL routines:ST_ACCEPT:sslv3 alert bad certificate
1652856152: Client <unknown> disconnected: Protocol error.
1652856152: Client mqtt-tls-rule disconnected.
```

**Comment by SuperRxan** [comment]
hi @cherrycl , I think the problem is you set the `"insecureSkipVerify": true` , please set it to true for this configuration.

``` code
{
   "id": "mqtt-tls-rule",
   "sql": "SELECT * FROM edgexsource",
   "actions":[
      {
         "mqtt":{
            "certificationPath": "/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.crt",
            "clientId": "mqtt-tls-rule",
            "insecureSkipVerify": false,
            "privateKeyPath": "/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.key",
            "rootCaPath": "/tmp/edgex/secrets/mqtt/client/edgex-kuiper/ca.crt",
            "server": "tcps://mqtt-broker:8883",
            "topic": "export"
         }
      }
   ]
}
```

**Comment by cherrycl** [comment]
Hi @SuperRxan I set `insecureSkipVerify: false` in sink and stream connection, both got an error. But the error messages are different, please reference the following log.

insecureSkipVerify: false
```
time="2022-06-01 09:19:13" level=error msg="The connection to edgex messagebus failed." file="edgex/edgex.go:126"
time="2022-06-01 09:19:13" level=error msg="can not create client for connection selector : edgex.mqttmsgbus have error Failed to connect to edgex message bus: An error occured while performing a 'Connect' operation: network Error : dial tcp 172.23.0.5:1883: connect: connection refused" file="clients/client_registy.go:93"
time="2022-06-01 09:19:13" level=error msg="found error when get edgex client, error Failed to connect to edgex message bus: An error occured while performing a 'Connect' operation: network Error : dial tcp 172.23.0.5:1883: connect: connection refused" file="source/edgex_source.go:80" rule=mqtt-rule
```
insecureSkipVerify: true
```
time="2022-05-18 14:42:32" level=error msg="The connection to edgex messagebus failed." file="edgex/edgex.go:126"
time="2022-05-18 14:42:32" level=error msg="can not create client for cfg : map[ClientId:edgexsource certificationpath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.crt format:json insecureskipverify:true messagetype:request optional_keepalive:50 port:8883 privatekeypath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.key protocol:tcps rootcapath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/ca.crt server:mqtt-broker topic:edgex/events/# type:mqtt] have error Failed to connect to edgex message bus: An error occured while performing a 'Connect' operation: network Error : x509: certificate signed by unknown authority" file="clients/client_registy.go:103"
time="2022-05-18 14:42:32" level=error msg="found error when get edgex client, error Failed to connect to edgex message bus: An error occured while performing a 'Connect' operation: network Error : x509: certificate signed by unknown authority" file="source/edgex_source.go:80" rule=mqtt-tls-rule
```

**Comment by SuperRxan** [comment]
```
environment:
      EDGEX__DEFAULT__PORT: 8883
      EDGEX__DEFAULT__PROTOCOL: tcps
      EDGEX__DEFAULT__SERVER: mqtt-broker
      EDGEX__DEFAULT__CLIENTID: edgexsource
      EDGEX__DEFAULT__OPTIONAL__CERTFILE: /tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.crt
      EDGEX__DEFAULT__OPTIONAL__KEYFILE: /tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.key
      EDGEX__DEFAULT__OPTIONAL__SKIPCERTVERIFY: 'true'
      EDGEX__DEFAULT__OPTIONAL__KEEPALIVE: 50
```

the way you set certffile and keyfile is incorrect

**Comment by cherrycl** [comment]
@SuperRxan Thanks for your suggestion.
I will test the stream connection first. I can't find any document to describe how to set configuration with TLS mqtt message bus on stream connection. Do you know where can I find it? As you said I cannot set cert and key on that way, then how to set it?
Thank you.

**Comment by cherrycl** [comment]
@SuperRxan When using the configuration you modified, still got error. The configurations are overrided, but edgex message bus still use port `1883` and protocol `tcp`.

```
time="2022-06-08 19:18:39" level=info msg="open source node with props map[ClientId:edgexsource connectionSelector:edgex.mqttMsgBus format:json messagetype:request optional:map[KeepAlive:50 certificationpath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.crt insecureskipverify:false privatekeypath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.key] optional_keepalive:50 port:8883 protocol:tcps server:mqtt-broker topic:edgex/events/# type:mqtt], concurrency: 1, bufferLength: 102400" file="node/source_node.go:93" rule=log-rule
time="2022-06-08 19:18:39" level=info msg="Start source edgexsource instance 0 successfully" file="node/source_node.go:126" rule=log-rule
time="2022-06-08 19:18:39" level=info msg="Set config 'connection.edgex.mqttmsgbus.server' to 'mqtt-broker' by environment variable" file="conf/load.go:127"
time="2022-06-08 19:18:39" level=info msg="Use configuration for edgex messagebus {{mqtt-broker 1883 tcp} {mqtt-broker 1883 tcp} mqtt map[KeepAlive:50]}" file="edgex/edgex.go:54"
time="2022-06-08 19:18:39" level=error msg="The connection to edgex messagebus failed." file="edgex/edgex.go:126"
time="2022-06-08 19:18:39" level=error msg="can not create client for connection selector : edgex.mqttmsgbus have error Failed to connect to edgex message bus: An error occured while performing a 'Connect' operation: network Error : dial tcp 192.168.96.5:1883: connect: connection refused" file="clients/client_registy.go:93"
```

**Comment by cloudxxx8** [comment]
@SuperRxan it is not an edgex issue, but for ekuiper specifically
We would like to confirm whether the TLS connection with MQTT broker is supported by eKuiper
thanks.

**Comment by SuperRxan** [comment]
@cherrycl  please paste all your configurations here


and check if your environment have this configuration, if have, please remove it

``` shell
 environment:
      EDGEX__DEFAULT__CONNECTIONSELECTOR: edgex.mqttmsgbus
```

**Comment by cherrycl** [comment]
@SuperRxan Thank you. I removed EDGEX__DEFAULT__CONNECTIONSELECTOR from the environment variable, and did the test again by the following configurations
```
environment:
      EDGEX__DEFAULT__PORT: 8883
      EDGEX__DEFAULT__PROTOCOL: tcps
      EDGEX__DEFAULT__SERVER: mqtt-broker
      EDGEX__DEFAULT__TOPIC: edgex/events/#
      EDGEX__DEFAULT__TYPE: mqtt
      EDGEX__DEFAULT__MESSAGETYPE: request
      EDGEX__DEFAULT__CLIENTID: edgexsource
      EDGEX__DEFAULT__OPTIONAL__CERTIFICATIONPATH: /tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.crt
      EDGEX__DEFAULT__OPTIONAL__PRIVATEKEYPATH: /tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.key
      EDGEX__DEFAULT__OPTIONAL__INSECURESKIPVERIFY: 'false'
      EDGEX__DEFAULT__OPTIONAL_KEEPALIVE: 50
      CONNECTION__EDGEX__MQTTMSGBUS__PROTOCOL: tcps
      CONNECTION__EDGEX__MQTTMSGBUS__SERVER: mqtt-broker
      CONNECTION__EDGEX__MQTTMSGBUS__PORT: 8883
      CONNECTION__EDGEX__MQTTMSGBUS__OPTIONAL__CERTIFICATIONPATH: /tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.crt
      CONNECTION__EDGEX__MQTTMSGBUS__OPTIONAL__PRIVATEKEYPATH: /tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.key
      CONNECTION__EDGEX__MQTTMSGBUS__OPTIONAL__ROOTCAPATH: /tmp/edgex/secrets/mqtt/client/edgex-kuiper/ca.crt
      CONNECTION__EDGEX__MQTTMSGBUS__OPTIONAL__INSECURESKIPVERIFY: 'false'
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__RESTPORT: 59720
      KUIPER__BASIC__DEBUG: "false"
```

I got the error `x509: certificate signed by unknown authority`. Capture the following error logs for your reference. 
```
time="2022-06-09 16:32:59" level=info msg="open source node with props map[ClientId:edgexsource format:json messagetype:request optional:map[KeepAlive:50 certificationpath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.crt insecureskipverify:false privatekeypath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.key] optional_keepalive:50 port:8883 protocol:tcps server:mqtt-broker topic:edgex/events/# type:mqtt], concurrency: 1, bufferLength: 102400" file="node/source_node.go:93" rule=log-rule
time="2022-06-09 16:32:59" level=info msg="Start source edgexsource instance 0 successfully" file="node/source_node.go:126" rule=log-rule
time="2022-06-09 16:32:59" level=info msg="Use configuration for edgex messagebus {{mqtt-broker 8883 tcps} {mqtt-broker 8883 tcps} mqtt map[KeepAlive:50 certificationpath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.crt insecureskipverify:false privatekeypath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.key]}" file="edgex/edgex.go:54"
time="2022-06-09 16:32:59" level=error msg="The connection to edgex messagebus failed." file="edgex/edgex.go:126"
time="2022-06-09 16:32:59" level=error msg="can not create client for cfg : map[ClientId:edgexsource format:json messagetype:request optional_keepalive:50 port:8883 protocol:tcps server:mqtt-broker topic:edgex/events/# type:mqtt] have error Failed to connect to edgex message bus: An error occured while performing a 'Connect' operation: network Error : x509: certificate signed by unknown authority" file="clients/client_registy.go:103"
time="2022-06-09 16:32:59" level=error msg="found error when get edgex client, error Failed to connect to edgex message bus: An error occured while performing a 'Connect' operation: network Error : x509: certificate signed by unknown authority" file="source/edgex_source.go:80" rule=log-rule
time="2022-06-09 16:32:59" level=info msg="EdgeX Source instance 0 Done." file="source/edgex_source.go:296" rule=log-rule
time="2022-06-09 16:32:59" level=info msg="source edgexsource done" file="node/source_node.go:114" rule=log-rule
time="2022-06-09 16:32:59" level=error msg="sending error: Failed to connect to edgex message bus: An error occured while performing a 'Connect' operation: network Error : x509: certificate signed by unknown authority" file="infra/saferun.go:52" rule=log-rule
time="2022-06-09 16:32:59" level=error msg="closing rule log-rule for error: Failed to connect to edgex message bus: An error occured while performing a 'Connect' operation: network Error : x509: certificate signed by unknown authority" file="server/rule_manager.go:119"
time="2022-06-09 16:32:59" level=error msg="sending error: <nil>" file="infra/saferun.go:52" rule=log-rule
```
Thank you.

**Comment by cherrycl** [comment]
@SuperRxan I updated the configuration below, and also got the error `x509: certificate signed by unknown authority`.
```
environment:
      EDGEX__DEFAULT__PORT: 8883
      EDGEX__DEFAULT__PROTOCOL: tcps
      EDGEX__DEFAULT__SERVER: mqtt-broker
      DGEX__DEFAULT__TOPIC: edgex/events/#
      EDGEX__DEFAULT__TYPE: mqtt
      EDGEX__DEFAULT__MESSAGETYPE: request
      EDGEX__DEFAULT__CLIENTID: edgexsource
      EDGEX__DEFAULT__OPTIONAL__CERTIFICATIONPATH: /tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.crt
      EDGEX__DEFAULT__OPTIONAL__PRIVATEKEYPATH: /tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.key
      EDGEX__DEFAULT__OPTIONAL__INSECURESKIPVERIFY: "true"
      EDGEX__DEFAULT__OPTIONAL_KEEPALIVE: 50
      CONNECTION__EDGEX__MQTTMSGBUS__PROTOCOL: tcps
      CONNECTION__EDGEX__MQTTMSGBUS__SERVER: mqtt-broker
      CONNECTION__EDGEX__MQTTMSGBUS__PORT: 8883
      CONNECTION__EDGEX__MQTTMSGBUS__OPTIONAL__CERTIFICATIONPATH: /tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.crt
      CONNECTION__EDGEX__MQTTMSGBUS__OPTIONAL__PRIVATEKEYPATH: /tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.key
      CONNECTION__EDGEX__MQTTMSGBUS__OPTIONAL__INSECURESKIPVERIFY: "true"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__RESTPORT: 59720
      KUIPER__BASIC__DEBUG: "false"
```
**Logs:**
```
time="2022-06-10 11:15:34" level=info msg="open source node with props map[ClientId:edgexsource format:json messagetype:request optional:map[KeepAlive:50 certificationpath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.crt insecureskipverify:true privatekeypath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.key] optional_keepalive:50 port:8883 protocol:tcps server:mqtt-broker topic:edgex/events/# type:mqtt], concurrency: 1, bufferLength: 102400" file="node/source_node.go:93" rule=log-rule
time="2022-06-10 11:15:34" level=info msg="Start source edgexsource instance 0 successfully" file="node/source_node.go:126" rule=log-rule
time="2022-06-10 11:15:34" level=info msg="Use configuration for edgex messagebus {{mqtt-broker 8883 tcps} {mqtt-broker 8883 tcps} mqtt map[KeepAlive:50 certificationpath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.crt insecureskipverify:true privatekeypath:/tmp/edgex/secrets/mqtt/client/edgex-kuiper/mqtt.key]}" file="edgex/edgex.go:54"
time="2022-06-10 11:15:34" level=info msg="open sink node 1 instances" file="node/sink_node.go:152" rule=log-rule
time="2022-06-10 11:15:34" level=info msg="Opening func collector" file="collector/func.go:50" rule=log-rule
time="2022-06-10 11:15:34" level=error msg="The connection to edgex messagebus failed." file="edgex/edgex.go:126"
time="2022-06-10 11:15:34" level=error msg="can not create client for cfg : map[ClientId:edgexsource format:json messagetype:request optional_keepalive:50 port:8883 protocol:tcps server:mqtt-broker topic:edgex/events/# type:mqtt] have error Failed to connect to edgex message bus: An error occured while performing a 'Connect' operation: network Error : x509: certificate signed by unknown authority" file="clients/client_registy.go:103"
time="2022-06-10 11:15:34" level=error msg="found error when get edgex client, error Failed to connect to edgex message bus: An error occured while performing a 'Connect' operation: network Error : x509: certificate signed by unknown authority" file="source/edgex_source.go:80" rule=log-rule
```
