### ISSUE TITLE
Edgex 2.3.0 use mqtt messagebus 

### ISSUE THREAD

**Issue by edgego** [lf-edge/ekuiper#2197]
Hi team, I use mqtt messagebus , and setup conf key for ekuiper:
	mod1:
		    messageType: request
		    optional:
		        ClientId: kuiper-rules-engine
		        KeepAlive: 500
		        Qos: 0
		        Retained: false
		        SkipCertVerify: true
		    port: 1883
		    protocol: tcp
		    server: edge-mqtt-broker
		    topic: edgex/events/device/Test-Device-Modbus-Profile/mod1#
		    type: mqtt

and create a rule based on datastream mod1, from ekuiper got error:

time="2023-08-18 02:37:59" level=error msg="Failed to subscribe to edgex messagebus with topic edgex/events/device/Test-Device-Modbus-Profile/mod1# has error : An error occured while performing a 'Subscribe' operation: connection lost before Subscribe completed." file="edgex/edgex.go:143"
time="2023-08-18 02:37:59" level=error msg="Failed to subscribe to edgex messagebus topic An error occured while performing a 'Subscribe' operation: connection lost before Subscribe completed.\n" file="edgex/edgex_source.go:94" source_pool=edgex.mod1

please kindly help how to setup conf key ! Thanks a lot!

**Comment by Rui-Gan** [comment]
```
mod1:
  messageType: request
  port: 1883
  protocol: tcp
  server: localhost
  topic: edgex/events/device/Test-Device-Modbus-Profile/mod1/#
  type: mqtt
  optional:
    ClientId: kuiper-rules-engine
    KeepAlive: 500
    Qos: 0
    Retained: false
    SkipCertVerify: true
```
Hi, you can try this configuration!
