### ISSUE TITLE
Changing the QoS on a Rule causes SQL logic error

### ISSUE THREAD

**Issue by Jubast** [lf-edge/ekuiper#2389]
**Environment**:

- eKuiper version: `1.11.4`
- OS: `docker`
```yaml
version: '3.9'
services:
  ekuiper:
    image: lfedge/ekuiper:1.11.4
    restart: unless-stopped
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://mqtt:1883"
    ports:
      - 9081:9081
    volumes:
      - ekuiper-etc:/kuiper/etc
      - ekuiper-data:/kuiper/data
      - ekuiper-plugins:/kuiper/plugins
      - ekuiper-log:/kuiper/log      
    depends_on:
      - mqtt
      
  ekuiper-manager:
    image: emqx/ekuiper-manager:1.9.3
    restart: unless-stopped
    ports:
      - 9082:9082
    environment:
      DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081"
    depends_on:
      - ekuiper
      
  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mqtt-config:/mosquitto/config:rw
      - mqtt-data:/mosquitto/data:rw
      - mqtt-log:/mosquitto/log:rw
      
  redis:
    image: redis:7.2.2
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data
    
      
volumes:
  ekuiper-etc:
  ekuiper-data:
  ekuiper-plugins:
  ekuiper-log:  
  mqtt-config:
  mqtt-data:
  mqtt-log:
  redis-data:
```

**What happened and what you expected to happen**:

Changing the QoS of a rule from `0` to `1` or `2`, causes a SQL logic error
```txt
{"status": "stopped", "message": "Stopped: topo d91489cd-5c94-4336-a801-966b727a2f81 create store error SQL logic error: near "-": syntax error (1)."}
```
```txt
time="2023-11-02 10:04:19" level=error msg="runtime error: <nil>" file="infra/saferun.go:55" rule=d91489cd-5c94-4336-a801-966b727a2f81
time="2023-11-02 10:04:19" level=info msg="Init rule with options &{Debug:false LogFilename: IsEventTime:false LateTol:1000 Concurrency:1 BufferLength:1024 SendMetaToSink:false SendError:true Qos:2 CheckpointInterval:60000 Restart:0xc0007d1f80 Cron: Duration: CronDatetimeRange:[]}" file="planner/planner.go:44"
time="2023-11-02 10:04:19" level=info msg="Opening stream" file="topo/topo.go:176" rule=d91489cd-5c94-4336-a801-966b727a2f81
time="2023-11-02 10:04:19" level=info msg="Rule d91489cd-5c94-4336-a801-966b727a2f81 is replaced." file="processor/rule.go:111"
time="2023-11-02 10:04:19" level=error msg="runtime error: topo d91489cd-5c94-4336-a801-966b727a2f81 create store error SQL logic error: near \"-\": syntax error (1)" file="infra/saferun.go:55" rule=d91489cd-5c94-4336-a801-966b727a2f81
time="2023-11-02 10:04:19" level=error msg="closing rule d91489cd-5c94-4336-a801-966b727a2f81 for error: topo d91489cd-5c94-4336-a801-966b727a2f81 create store error SQL logic error: near \"-\": syntax error (1)" file="rule/ruleState.go:211"
time="2023-11-02 10:04:19" level=error msg="runtime error: <nil>" file="infra/saferun.go:55" rule=d91489cd-5c94-4336-a801-966b727a2f81
time="2023-11-02 10:04:19" level=info msg="Rule d91489cd-5c94-4336-a801-966b727a2f81 is update." file="processor/rule.go:89"
```

**How to reproduce it (as minimally and precisely as possible)**:
1.) MQTT Source (Address: `tcp://mqtt:1883`, Protocol version: `3.1.1`, QoS level: `2`)
2.) Create a Stream LogStream (Stream Type: `mqtt`,  Stream Format: `JSON`, Timestamp Field: `Timestamp`)
3.) Create a new rule "SELECT COUNT(*) FROM LogStream" with QoS option set to `2`
