### ISSUE TITLE
Failed to connect to EdgeX security message bus

### ISSUE THREAD

**Issue by lindseysimple** [lf-edge/ekuiper#3697]
**Environment**:

- eKuiper version (e.g. `1.3.0`): v2.1.3
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`): MAC OS 15.0.1
- EdgeX version: v4

**What happened and what you expected to happen**:

While launching EdgeX services in security mode,  `mqtt-broker` is configured with username and password settings, and each EdgeX service should connect to the `mqtt-broker` successfully.

The `The connection to edgex messagebus failed.` error occurred in ekuiper service log as below, while all the other service can connect to `mqtt-broker` successfully:

```
level=INFO ts=2025-05-14T17:45:12.352053232+08:00 app=security-bootstrapper source=command.go:214 msg="Connected to tcp://edgex-security-bootstrapper:54329"       
Wed May 14 17:45:12 CST 2025 Starting Kuiper ...                                                                                                                  
time="2025-05-14T17:45:12+08:00" level=info msg="register source redisSub" file="server/server.go:145
......
time="2025-05-14T17:45:13+08:00" level=info msg="register component service" file="server/server.go:199"          
time="2025-05-14T17:45:13+08:00" level=info msg="register component template" file="server/server.go:199"       
time="2025-05-14T17:45:13+08:00" level=info msg="register component meta" file="server/server.go:199"                                                              
time="2025-05-14T17:45:13+08:00" level=info msg="register component plugin" file="server/server.go:199"                                                            
time="2025-05-14T17:45:13+08:00" level=info msg="register component portable" file="server/server.go:199"
time="2025-05-14T17:45:13+08:00" level=info msg="register component prometheus" file="server/server.go:199"                                
time="2025-05-14T17:45:13+08:00" level=info msg="write conf key:connections.edgex.mqttmsgbus " file="conf/yaml_config_storage.go:138" 
time="2025-05-14T17:45:13+08:00" level=info msg="register component prometheus" file="server/server.go:199"               
time="2025-05-14T17:45:13+08:00" level=info msg="write conf key:connections.edgex.mqttmsgbus " file="conf/yaml_config_storage.go:138"                             
time="2025-05-14T17:45:13+08:00" level=info msg="Use configuration for edgex messagebus {{edgex-mqtt-broker 1883 tcp} mqtt map[]}" file="client/edgex.go:113"     
time="2025-05-14T17:45:13+08:00" level=info msg="Set config 'connection.edgex.mqttmsgbus.server' to 'edgex-mqtt-broker' by environment variable" file="conf/load.go
:141"                                                                                                                                                             
time="2025-05-14T17:45:13+08:00" level=info msg="Set config 'connection.edgex.mqttmsgbus.optional.clientid' to 'kuiper-rules-engine' by environment variable" file=
"conf/load.go:141"                                                                                                                                                
time="2025-05-14T17:45:13+08:00" level=info msg="Set config 'connection.edgex.mqttmsgbus.type' to 'mqtt' by environment variable" file="conf/load.go:141"         
time="2025-05-14T17:45:13+08:00" level=info msg="Set config 'connection.edgex.mqttmsgbus.optional.keepalive' to '500' by environment variable" file="conf/load.go:1
41"                                                                                                                                                               
time="2025-05-14T17:45:13+08:00" level=info msg="Set config 'connection.edgex.mqttmsgbus.protocol' to 'tcp' by environment variable" file="conf/load.go:141"      
time="2025-05-14T17:45:13+08:00" level=info msg="Set config 'edgex.default.optional.clientid' to 'kuiper-rules-engine' by environment variable" file="conf/load.go:
141"                                                                                                                                                              
time="2025-05-14T17:45:13+08:00" level=info msg="Set config 'edgex.default.topic' to 'edgex/events/device/#' by environment variable" file="conf/load.go:141"     
time="2025-05-14T17:45:13+08:00" level=info msg="Set config 'edgex.default.connectionselector' to 'mqttmsgbus' by environment variable" file="conf/load.go:141"
time="2025-05-14T17:45:13+08:00" level=info msg="Set config 'edgex.default.protocol' to 'tcp' by environment variable" file="conf/load.go:141"
time="2025-05-14T17:45:13+08:00" level=info msg="Set config 'edgex.default.messagetype' to 'request' by environment variable" file="conf/load.go:141"
time="2025-05-14T17:45:13+08:00" level=info msg="Set config 'edgex.default.type' to 'mqtt' by environment variable" file="conf/load.go:141"
time="2025-05-14T17:45:13+08:00" level=info msg="Set config 'edgex.default.optional.keepalive' to '500' by environment variable" file="conf/load.go:141"
time="2025-05-14T17:45:13+08:00" level=info msg="Set config 'edgex.edgex_security_secret_store' to 'true' by environment variable" file="conf/load.go:141"
time="2025-05-14T17:45:13+08:00" level=info msg="Set config 'edgex.default.server' to 'edgex-mqtt-broker' by environment variable" file="conf/load.go:141"
time="2025-05-14T17:45:13+08:00" level=error msg="The connection to edgex messagebus failed." file="client/edgex.go:61"
time="2025-05-14T17:45:13+08:00" level=info msg="connect to local broker for control channel" file="sig/control.go:54"
time="2025-05-14T17:45:13+08:00" level=error msg="fail to read init file: open /kuiper/data/init.json: no such file or directory" file="server/rule_init.go:45"
time="2025-05-14T17:45:13+08:00" level=info msg="Starting rules" file="server/server.go:229"                      
time="2025-05-14T17:45:13+08:00" level=info msg="metrics dump disabled" file="metrics/metrics_dump.go:79"       
time="2025-05-14T17:45:13+08:00" level=info msg="start patroling schedule rule state" file="server/rule_init.go:100"                                              
time="2025-05-14T17:45:13+08:00" level=info msg="register rest endpoint for component schema" file="server/rest.go:228"
time="2025-05-14T17:45:13+08:00" level=info msg="register rest endpoint for component service" file="server/rest.go:228"
time="2025-05-14T17:45:13+08:00" level=info msg="register rest endpoint for component template" file="server/rest.go:228"                  
time="2025-05-14T17:45:13+08:00" level=info msg="register rest endpoint for component meta" file="server/rest.go:228"
time="2025-05-14T17:45:13+08:00" level=info msg="register rest endpoint for component plugin" file="server/rest.go:228"
time="2025-05-14T17:45:13+08:00" level=info msg="register rest endpoint for component portable" file="server/rest.go:228"
time="2025-05-14T17:45:13+08:00" level=info msg="register rest endpoint for component prometheus" file="server/rest.go:228"
time="2025-05-14T17:45:13+08:00" level=info msg="start service rpc" file="server/server.go:267"
time="2025-05-14T17:45:13+08:00" level=info msg="start service pprof" file="server/server.go:267"
time="2025-05-14T17:45:13+08:00" level=info msg="start service prometheus" file="server/server.go:267"
time="2025-05-14T17:45:13+08:00" level=info msg="using ListenMode 'http'" file="server/server.go:74"
time="2025-05-14T17:45:13+08:00" level=info msg="register conf manager service" file="server/import_export.go:53"
time="2025-05-14T17:45:13+08:00" level=info msg="register conf manager plugin" file="server/import_export.go:53"
time="2025-05-14T17:45:13+08:00" level=info msg="register conf manager portable" file="server/import_export.go:53"
time="2025-05-14T17:45:13+08:00" level=info msg="register conf manager schema" file="server/import_export.go:53"
time="2025-05-14T17:45:13+08:00" level=info msg="Serving kuiper (version - 2.1.3) on port 20498, and restful api on http://0.0.0.0:59720." file="server/server.go:2
80"
Serving kuiper (version - 2.1.3) on port 20498, and restful api on http://0.0.0.0:59720.
time="2025-05-14T17:45:18+08:00" level=warning msg="found error when connecting for mqtt control channel: timeout" file="sig/control.go:80"
```

**How to reproduce it (as minimally and precisely as possible)**:

Launch EdgeX services with the following `ekuiper` and `mqtt-broker` service definition based on the EdgeX [docker compose file](https://github.com/edgexfoundry/edgex-compose/blob/main/docker-compose.yml):
```
  mqtt-broker:
    command: "/usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf"
    entrypoint: [ "/edgex-init/messagebus_wait_install.sh" ]
    environment:
      <<: *security-common-variables
      BROKER_TYPE: mosquitto
      CONF_DIR: /edgex-init/bootstrap-mosquitto/res
      ENTRYPOINT: /docker-entrypoint.sh /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf
    container_name: edgex-mqtt-broker
    hostname: edgex-mqtt-broker
    image: eclipse-mosquitto:2.0
    networks:
      edgex-network: null
    volumes:
      - mqtt:/mosquitto
      - edgex-init:/edgex-init:ro
      - /tmp/edgex/secrets/security-bootstrapper-messagebus:/tmp/edgex/secrets/security-bootstrapper-messagebus:ro,z
    read_only: true
    ports:
      - "1883:1883"
    restart: always
    security_opt:
      - no-new-privileges:true
    user: "root:root"
    depends_on:
      - security-bootstrapper
      - security-secretstore-setup
...
  rules-engine:
    container_name: edgex-kuiper
    depends_on:
      database:
        condition: service_started
        required: true
      mqtt-broker:
        condition: service_started
        required: true
      security-bootstrapper:
        condition: service_started
        required: true
      security-secretstore-setup:
        condition: service_started
        required: true
    entrypoint:
      - /edgex-init/kuiper_wait_install.sh
    environment:
      <<: *security-common-variables
      CONNECTION__EDGEX__MQTTMSGBUS__OPTIONAL__CLIENTID: kuiper-rules-engine
      CONNECTION__EDGEX__MQTTMSGBUS__OPTIONAL__KEEPALIVE: "500"
      CONNECTION__EDGEX__MQTTMSGBUS__PORT: "1883"
      CONNECTION__EDGEX__MQTTMSGBUS__PROTOCOL: tcp
      CONNECTION__EDGEX__MQTTMSGBUS__SERVER: edgex-mqtt-broker
      CONNECTION__EDGEX__MQTTMSGBUS__TYPE: mqtt
      EDGEX__DEFAULT__OPTIONAL__CLIENTID: kuiper-rules-engine
      EDGEX__DEFAULT__OPTIONAL__KEEPALIVE: "500"
      EDGEX__DEFAULT__PORT: "1883"
      EDGEX__DEFAULT__PROTOCOL: tcp
      EDGEX__DEFAULT__SERVER: edgex-mqtt-broker
      EDGEX__DEFAULT__TOPIC: edgex/events/device/#
      EDGEX__DEFAULT__MESSAGETYPE: request
      EDGEX__DEFAULT__TYPE: mqtt
      EDGEX__DEFAULT__CONNECTIONSELECTOR: mqttmsgbus
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__ENABLEOPENZITI: "false"
      KUIPER__BASIC__RESTPORT: "59720"
    hostname: edgex-kuiper
    image: lfedge/ekuiper:v2.1.3
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 59720
        published: "59720"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: kuiper:kuiper
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: volume
        source: kuiper-data
        target: /kuiper/data
        volume: {}
      - type: volume
        source: kuiper-etc
        target: /kuiper/etc
        volume: {}
      - type: volume
        source: kuiper-log
        target: /kuiper/log
        volume: {}
      - type: volume
        source: kuiper-plugins
        target: /kuiper/plugins
        volume: {}
      - type: volume
        source: kuiper-sources
        target: /kuiper/etc/sources
        volume: {}
      - type: volume
        source: kuiper-connections
        target: /kuiper/etc/connections
        volume: {}
      - type: volume
        source: edgex-init
        target: /edgex-init
        read_only: true
        volume: {}
```

**Anything else we need to know?**:

Have attached to the ekuiper service container and checked the content `connection.yaml` and other configuration files as below, the message bus username/password have been retrieved from secret store and added to the files:
```
/kuiper/etc/connections $ cat connection.yaml 

edgex:
  mqttMsgBus: #connection key
    protocol: tcp
    server: localhost
    port: 1883
    type: mqtt
    optional:
      Username: msgbususer
      Password: w46fV2h+yJEsq/e8n+DsXP9jSskVsEYtYrIt2OAQd4O1

/kuiper/etc/sources $ cat edgex.yaml 

application_conf:
  port: 5571
  protocol: tcp
  server: localhost
  topic: application
default:
  optional:
    Username: msgbususer
    Password: w46fV2h+yJEsq/e8n+DsXP9jSskVsEYtYrIt2OAQd4O1
  port: 1883
  protocol: tcp
  server: localhost
  connectionSelector: edgex.mqttMsgBus
  topic: rules-events
  type: mqtt
mqtt_conf:
  optional:
    ClientId: client1
  port: 1883
  protocol: tcp
  server: localhost
  topic: events
  type: mqtt
```
