### ISSUE TITLE
Support to connect to EdgeX v2 message bus directly

### ISSUE THREAD

**Issue by ngjaying** [lf-edge/ekuiper#896]
Currently, we connect to EdgeX by app service by default. It is sometimes critical to directly connect to the message bus for performance. Also, EdgeX Ireland supports to filter by topics in the message bus which is convenient for mutliple rules.

When subscribing to the message bus topic, the received message type is request intead of event. We need to add support for the request type in the EdgeX source.

**Comment by gao270615179** [comment]
Also need support redis as message bus.

**Comment by ngjaying** [comment]
> Also need support redis as message bus.

Could you please elaborate more? Do you mean support redis message bus in EdgeX? If so, that is already supported and it is the default.

**Comment by gao270615179** [comment]
Sorry, I have seen the default message bus type was ZeroMQ in edgex_source.go:L63 and `currently two types of message buses are supported(zero and mqtt)` was writed in rules/sources/edgex.md. But it does support redis message bus.

By the way, will it support to get username and password of redis/mqtt from edgex secret store(vault)?

**Comment by ngjaying** [comment]
> Sorry, I have seen the default message bus type was ZeroMQ in edgex_source.go:L63 and `currently two types of message buses are supported(zero and mqtt)` was writed in rules/sources/edgex.md. But it does support redis message bus.

Ah, the doc needs an update

> By the way, will it support to get username and password of redis/mqtt from edgex secret store(vault)?

I don't quite know about the secret store in edgex. Let me check and reply you later.

**Comment by gao270615179** [comment]
You can see this doc: [Secret-Provider-For-All](https://docs.edgexfoundry.org/2.0/design/adr/014-Secret-Provider-For-All/)

and EdgeX v2 can provide redis password for kuiper by setting environment ADD_KNOWN_SECRETS/ADD_SECRETSTORE_TOKENS after edgexfoundry security secretstore setup.

kuiper will need more configuration about secret provider in etc/sources/edgex.yaml

**Comment by ngjaying** [comment]
Thanks, we'll take a look

**Comment by ngjaying** [comment]
> You can see this doc: [Secret-Provider-For-All](https://docs.edgexfoundry.org/2.0/design/adr/014-Secret-Provider-For-All/)
> 
> and EdgeX v2 can provide redis password for kuiper by setting environment ADD_KNOWN_SECRETS/ADD_SECRETSTORE_TOKENS after edgexfoundry security secretstore setup.
> 
> kuiper will need more configuration about secret provider in etc/sources/edgex.yaml

The default docker compose in Ireland will inject the credential into eKuiper through volume mount:
https://github.com/edgexfoundry/edgex-compose/blob/ireland/docker-compose.yml

In eKuiper, edgex.yaml has a configuration for username/password in the optional part. The docker compose will set this configuration or you can set this manually.

```yaml
default:
  protocol: tcp
  server: localhost
  port: 5563
  topic: events
#  Below is optional configurations settings for mqtt
#  type: mqtt
  optional:
#    ClientId: client1
      Username: user1
      Password: password
#    Qos: 1
#    KeepAlive: 5000
#    Retained: true/false
#    ConnectionPayload:
#    CertFile:
#    KeyFile:
#    CertPEMBlock:
#    KeyPEMBlock:
#    SkipCertVerify: true/false
```
